import test from 'node:test';
import assert from 'node:assert/strict';

import { loadPromptTemplate } from '../../dist/llm/prompts.js';

test('memory recaller prompt composes recall context with a soft budget', () => {
  const prompt = loadPromptTemplate('memory_recaller');

  assert.match(prompt.system, /memory recall agent/i);
  assert.match(prompt.system, /different agents, sessions, and contexts/i);
  assert.match(prompt.system, /integrate the relevant memories/i);
  assert.match(prompt.system, /filter out unrelated content/i);
  assert.match(prompt.system, /main agent should see/i);
  assert.match(prompt.system, /identify the query intent/i);
  assert.match(prompt.system, /General rules/);
  assert.match(prompt.system, /Do not answer the query/);
  assert.match(prompt.system, /Prepare memory for the main agent/);
  assert.match(prompt.system, /Do not compute, finalize, or decide the answer/);
  assert.match(prompt.system, /especially time expressions/);
  assert.match(prompt.system, /compress context that is not useful or unrelated to the query/);
  assert.match(prompt.system, /Do not invent facts or make inferences/);
  assert.match(prompt.system, /candidate memories conflict/);
  assert.match(prompt.system, /soft target/);
  assert.match(prompt.system, /preserve relevant memory details and accuracy/);
  assert.match(prompt.system, /Factual recall/);
  assert.match(prompt.system, /Judgment recall/);
  assert.match(prompt.system, /gather directly relevant facts around the query/);
  assert.match(prompt.system, /Keep concrete values and relevant context/);
  assert.match(prompt.system, /compatible parts from multiple candidates/);
  assert.match(prompt.system, /keep distinct subjects, events, times, or conditions separate/);
  assert.match(prompt.system, /Do not replace concrete facts with uncertainty/);
  assert.match(prompt.system, /judgment, match, preference, likelihood, comparison, or inference based on memory/);
  assert.match(prompt.system, /positive and negative memory signals and details/);
  assert.match(prompt.system, /limits, uncertainty, or mismatches/);
  assert.match(prompt.system, /Do not answer the judgment/);
  assert.match(prompt.userTemplate, /Budget:/);
  assert.doesNotMatch(prompt.userTemplate, /General rules/);
  assert.doesNotMatch(prompt.userTemplate, /Factual recall/);
  assert.match(prompt.userTemplate, /Return refs for the memory candidates used to write the content/);
  assert.match(prompt.userTemplate, /Return JSON only/);
  assert.match(prompt.userTemplate, /"refs"/);
});

test('chat domain prompt provides category guidance without session memory workflow schema', () => {
  const template = loadPromptTemplate('chat');
  const system = template.system;

  assert.match(system, /Chat memory categories/);
  assert.match(system, /Session memory thread definition/);
  assert.match(system, /subject session memory thread tracks one coherent subject that can develop over time/);
  assert.match(system, /narrower than the whole conversation and more stable than a single message/);
  assert.match(system, /Route a new span to a subject thread only when it updates, answers, clarifies, corrects, supports, or directly continues that subject/);
  assert.doesNotMatch(system, /Use `update` plus `add`/);
  assert.doesNotMatch(system, /Chat filtering/);
  assert.doesNotMatch(system, /Extraction granularity/);
  assert.match(system, /Use categories only to organize snapshot content/);
  assert.match(system, /First write the memory content, then choose one or more categories/);
  assert.match(system, /Store useful conclusions, answers, states, plans, preferences, or reusable facts, not conversation acts/);
  assert.match(system, /Fold chat evidence into the relevant existing context/);
  assert.doesNotMatch(system, /greetings, small talk, filler/);
  assert.doesNotMatch(system, /pure questions, temporary status updates/);
  assert.doesNotMatch(system, /descriptive details, transition remarks, pure questions, one-off actions/);
  assert.match(system, /stable or recurring like/);
  assert.match(system, /explicit, non-trivial, and useful beyond the current conversation/);
  assert.doesNotMatch(system, /Prefer `Fact` for one-time events, described objects, and answerable details/);
  assert.doesNotMatch(system, /Prefer `Decision` when the main signal is what someone plans, chooses, or commits to do/);
  assert.doesNotMatch(system, /Prefer `Preference` only when the signal is stable or recurring/);
  assert.doesNotMatch(system, /Prefer `Entity` only for stable attributes, not one-time events involving the entity/);
  assert.match(system, /When chat memory contains a time expression/);
  assert.match(system, /normalize it to absolute time using grounded context anchors when possible/);
  assert.doesNotMatch(system, /Extract useful absolute time from context when available/);
  assert.doesNotMatch(system, /memory-get/);
  assert.doesNotMatch(system, /If an extraction or `contextRefs\.summary` would still contain unresolved relative time/);
  assert.match(system, /useful memory that does not fit above/);
  assert.doesNotMatch(system, /Extraction definition/);
  assert.doesNotMatch(system, /Thread title/);
  assert.doesNotMatch(system, /Thread summary/);
  assert.doesNotMatch(system, /memory_get/);
  assert.doesNotMatch(system, /extractionChanges/);
  assert.doesNotMatch(system, /extractionDelta/);
  assert.doesNotMatch(system, /Return exactly one JSON object/);
});

test('thread session memory prompt uses generic recall-ready memory guidance', () => {
  const template = loadPromptTemplate('thread_extracting');
  const system = template.system;

  assert.doesNotMatch(system, /Extraction state: the complete current list of extractions this thread should keep/);
  assert.match(system, /Snapshot sections/);
  assert.match(system, /Extractions are compact semantic memory units for future retrieval and later updates/);
  assert.match(system, /Memory Signals are AGENTS\.md\/MEMORY\.md-style operating instructions for future agents/);
  assert.match(system, /Skill Signals are compact indexes for reusable workflow candidates that could later become a `SKILL\.md`/);
  assert.match(system, /Skill Details hold reusable procedure details only for accepted Skill Signals/);
  assert.match(system, /Extraction unit rules/);
  assert.doesNotMatch(system, /organizes related session content for future recall/);
  assert.match(system, /durable topic: a decision, requirement, preference, correction, finding, problem, solution, risk, task state, or open question/);
  assert.match(system, /Merge repeated corrections or refinements of the same topic/);
  assert.match(system, /Split an extraction unit when its semantic index would exceed budget/);
  assert.match(system, /extractor that updates a session memory snapshot from new conversation turns/);
  assert.match(system, /Use the current snapshot title, summaries, signal sections, and current batch turns/);
  assert.doesNotMatch(system, /existingSnapshotContent/);
  assert.match(system, /Return a Markdown snapshot patch, not a full snapshot/);
  assert.match(system, /# <Session Title>/);
  assert.match(system, /### Title/);
  assert.match(system, /Session title: usually 4-8 tokens/);
  assert.match(system, /Extraction titles are short UI labels: usually 3-10 words, hard maximum 16 words/);
  assert.match(system, /## Summary/);
  assert.match(system, /## Extractions/);
  assert.doesNotMatch(system, /Routing has already selected the fragments for this thread/);
  assert.doesNotMatch(system, /routed fragments/);
  assert.doesNotMatch(system, /Fragment:/);
  assert.doesNotMatch(system, /rewrite clear relative dates or periods into absolute dates or periods/);
  assert.doesNotMatch(system, /`yesterday`, `tomorrow`, `last week`, `last month`, and `last year`/);
  assert.doesNotMatch(system, /Fallback inspection/);
  assert.doesNotMatch(system, /batches of up to 5/);
  assert.doesNotMatch(system, /starting from the first sourceRef/);
  assert.match(system, /Filter greetings, acknowledgements, filler, and pure transcript mechanics/);
  assert.match(system, /Create or update an extraction unit for a durable topic/);
  assert.doesNotMatch(system, /Remove or rewrite units that are outdated, wrong, or duplicated/);
  assert.doesNotMatch(system, /When normalizing a time expression/);
  assert.doesNotMatch(system, /Keep the original remembered object in `\[Extraction\]`/);
  assert.doesNotMatch(system, /do not replace it with a broader summary or leave it only in `\[Context\]`/);
  assert.match(system, /If source content is valuable as a semantic retrieval index, extract and write it into the extraction; otherwise use citations to index supporting source turns or exact passages/);
  assert.match(system, /Avoid transcript-like detail: routine chronology, repeated progress, command\/test\/CI\/log details, and implementation steps/);
  assert.match(system, /Extractions are not better because they contain more text; prefer dense, retrieval-oriented content over volume/);
  assert.doesNotMatch(system, /can be remembered content when they describe something specific/);
  assert.doesNotMatch(system, /Granularity:/);
  assert.doesNotMatch(system, /memory unit purpose/);
  assert.doesNotMatch(system, /Memory anchors/);
  assert.doesNotMatch(system, /1-3 memory anchors/);
  assert.doesNotMatch(system, /Anchor names/);
  assert.doesNotMatch(system, /Memory categories/);
  assert.doesNotMatch(system, /Domain guidance/);
  assert.doesNotMatch(system, /domain_prompt/);
  assert.doesNotMatch(system, /Category selection:/);
  assert.doesNotMatch(system, /Prefer the most specific category over `Fact` when an extraction describes/);
  assert.doesNotMatch(system, /Extraction definition/);
  assert.doesNotMatch(system, /Recall-ready writing/);
  assert.doesNotMatch(system, /Derivation style/);
  assert.doesNotMatch(system, /Fact quality/);
  assert.match(system, /Session title:/);
  assert.match(system, /Extraction titles are short UI labels/);
  assert.doesNotMatch(system, /key person\/entity\/object plus concrete topic, activity, artifact, plan, relationship, or state/);
  assert.doesNotMatch(system, /stable thread subject, not the latest turn/);
  assert.doesNotMatch(system, /stay neutral and concrete without overstating long-term meaning/);
  assert.doesNotMatch(system, /meta labels/);
  assert.doesNotMatch(system, /Prefer 6-14 words/);
  assert.match(system, /4-8 tokens/);
  assert.match(system, /Summary/);
  assert.doesNotMatch(system, /Thread state/);
  assert.doesNotMatch(system, /contextRefs/);
  assert.doesNotMatch(system, /snapshotContent/);
  assert.doesNotMatch(system, /Include a `contextRef` for every new turn whose information is used/);
  assert.doesNotMatch(system, /clarifies ownership, time, attribution, or status/);
  assert.doesNotMatch(system, /openQuestions/);
  assert.doesNotMatch(system, /nextSteps/);
  assert.doesNotMatch(system, /roughly 1000 characters/);
  assert.doesNotMatch(system, /roughly 500 characters/);
});

test('session memory prompt preserves the current extraction schema', () => {
  const template = loadPromptTemplate('thread_extracting');
  const system = template.system;

  assert.match(system, /Each extraction must include `### Title` and `### Summary`/);
  assert.match(system, /Session signal sections/);
  assert.match(system, /Use two signal sections in this order: `## Memory Signals`, `## Skill Signals`/);
  assert.match(system, /IMPORTANT: Before recording a Memory Signal or Skill Signal/);
  assert.match(system, /first verify whether the signal would still matter after the current task is completed or the current session ends/);
  assert.match(system, /if not, do not record it as a signal/);
  assert.doesNotMatch(system, /ask whether it would still be useful if copied into AGENTS\.md for future work/);
  assert.doesNotMatch(system, /verify that it is context-independent and remains reusable after the current task ends/);
  assert.doesNotMatch(system, /lightweight signal/i);
  assert.doesNotMatch(system, /Lightweight signals are context-independent, future-session reusable agent instructions/);
  assert.doesNotMatch(system, /when it can guide another session without the original conversation, current task state, or assistant response context/);
  assert.match(system, /Use user prompts as evidence for Memory Signals and Skill Signals/);
  assert.match(system, /Non-user materials are reference-only; a user prompt can turn referenced material into signal evidence only when it explicitly names or restates the specific signal/);
  assert.doesNotMatch(system, /Instructions that only define the active task's deliverable belong in Extractions, not lightweight signal sections/);
  assert.doesNotMatch(system, /unless the user explicitly asks to remember or reuse them as future-agent instructions beyond the active task/);
  assert.doesNotMatch(system, /Muninn memory output behavior/);
  assert.doesNotMatch(system, /Memory Signals must describe how future agents should work/);
  assert.doesNotMatch(system, /Instructions that only constrain the active task's output belong in Extractions/);
  assert.doesNotMatch(system, /Instructions that only define what the active task is producing or how that output should behave belong in Extractions/);
  assert.doesNotMatch(system, /Do not put task artifacts or task-local state in lightweight signal sections/);
  assert.doesNotMatch(system, /product requirements, prompt\/spec\/doc drafts, implementation decisions, feature decisions, PR\/review\/test\/command status, and task-local instructions belong in Extractions/);
  assert.doesNotMatch(system, /`## Signals`/);
  assert.doesNotMatch(system, /Do not put feature-specific design decisions, PR state, review findings, command results, or test status in Signals/);
  assert.match(system, /Approval-only prompts such as "yes", "ok", "continue", or "do that"/);
  assert.match(system, /not reusable signal evidence unless they explicitly say to remember or reuse a future-session rule/);
  assert.match(system, /explicitly names or restates the specific signal/);
  assert.match(system, /Preserve the user's intended meaning, scope, and constraints/);
  assert.match(system, /Do not broaden a signal beyond what the supporting prompt explicitly supports/);
  assert.match(system, /Merge similar signals using the latest prompt-supported wording and scope, and merge their supporting evidence labels/);
  assert.match(system, /If newer user-prompt evidence changes, narrows, or rejects an earlier signal/);
  assert.match(system, /do not carry forward contradicted evidence labels/);
  assert.match(system, /Write natural-language signals and Skill Details prose in the dominant language of the current batch's user instructions/);
  assert.match(system, /ignore quoted, pasted, or drafted content for language choice/);
  assert.match(system, /preserve identifiers exactly/);
  assert.doesNotMatch(system, /Write natural-language Memory Signals, Skill Signals, Open Questions, and Skill Details prose in the language of the user prompt that supports them/);
  assert.doesNotMatch(system, /Write natural-language Memory Signals, Skill Signals, and Open Questions in the language of the user prompt that supports the signal/);
  assert.doesNotMatch(system, /not the language of quoted, pasted, or drafted task content/);
  assert.doesNotMatch(system, /conversation's primary language/);
  assert.doesNotMatch(system, /primary language of the supporting user prompt/);
  assert.doesNotMatch(system, /preserve code and project identifiers/);
  assert.match(system, /Write signals as direct future-agent instructions, not meta descriptions about the user/);
  assert.doesNotMatch(system, /future-agent guidance/);
  assert.match(system, /avoid phrasing like "The user prefers concise replies"/);
  assert.match(system, /write the guidance itself instead/);
  assert.doesNotMatch(system, /用户偏好/);
  assert.doesNotMatch(system, /record normalized guidance, not transcript mechanics/);
  assert.doesNotMatch(system, /Skills may use nested bullets only for compact skill-card fields/);
  assert.doesNotMatch(system, /Skills may use nested bullets for workflow triggers, steps, checks, and expected output/);
  assert.match(system, /Memory Signals/);
  assert.match(system, /Memory Signals are AGENTS\.md\/MEMORY\.md-style operating instructions for future agents: standing user preferences/);
  assert.match(system, /direct corrections to agent behavior/);
  assert.match(system, /edit\/review style/);
  assert.match(system, /recurring environment quirks/);
  assert.match(system, /explicit remember requests/);
  assert.match(system, /narrow repo\/module boundaries/);
  assert.match(system, /Memory Signals are not task-bound rules or facts about the current artifact's behavior/);
  assert.match(system, /output format, prompt behavior, schema\/API\/data model, tests, or review deliverables/);
  assert.match(system, /keep them only when they are direct future-agent instructions, explicit remember\/reuse requests, or narrow repo\/module boundaries, and do not duplicate instructions already added to AGENTS\.md or MEMORY\.md in the current task/);
  assert.doesNotMatch(system, /Do not record task-bound facts as Memory Signals/);
  assert.doesNotMatch(system, /A direct user correction may become a Memory Signal when it tells future agents what to avoid or prefer beyond the current task/);
  assert.doesNotMatch(system, /record only the corrected action, with the user's narrow scope and constraints/);
  assert.doesNotMatch(system, /Memory Signals may capture durable repo\/module boundaries/);
  assert.doesNotMatch(system, /not the task-specific decisions, rationale, or implementation state that produced them/);
  assert.doesNotMatch(system, /Task-bound facts include:/);
  assert.doesNotMatch(system, /Design or implementation decisions about the artifact being built, edited, or reviewed\./);
  assert.doesNotMatch(system, /Design or implementation decisions about the artifact being built, edited, or reviewed that do not define a durable repo\/module boundary/);
  assert.doesNotMatch(system, /Requirements or acceptance criteria for the current prompt, spec, doc, test, UI, API, schema, or storage change/);
  assert.doesNotMatch(system, /Task execution state such as PR\/CI\/review status, command results, logs, reproduction notes, import progress, or validation progress/);
  assert.doesNotMatch(system, /Investigation findings or tradeoffs that explain the current solution but do not tell future agents how to act/);
  assert.doesNotMatch(system, /A project constraint may be a Memory Signal only when/);
  assert.doesNotMatch(system, /future coding agents/);
  assert.doesNotMatch(system, /directly constrain how future agents should edit code/);
  assert.doesNotMatch(system, /Memory Signals are AGENTS\.md\/MEMORY\.md-style operating instructions: recurring preferences/);
  assert.doesNotMatch(system, /durable project conventions/);
  assert.doesNotMatch(system, /explicit requests to remember or reuse non-workflow instructions beyond the active task/);
  assert.doesNotMatch(system, /user-explicit requests to remember or reuse non-workflow instructions/);
  assert.doesNotMatch(system, /reusable future-session memory candidates/);
  assert.doesNotMatch(system, /Memory Signals may only be created, rewritten, or strengthened by user prompts/);
  assert.match(system, /If the user explicitly asks to remember or reuse an instruction or simple workflow in future sessions/);
  assert.match(system, /Keep each Memory Signal as one concise, context-independent top-level bullet/);
  assert.doesNotMatch(system, /Guidance: standing behavior guidance/);
  assert.match(system, /Skill Signals are compact indexes for reusable workflow candidates that could later become a `SKILL\.md`/);
  assert.match(system, /Skill Signals should name class-level reusable workflows, not one-session task artifacts/);
  assert.match(system, /avoid names based on PR numbers, error strings, feature codenames, or today's fix\/debug task/);
  assert.match(system, /Installed, invoked, or referenced agent skills are execution context, not Skill Signals/);
  assert.match(system, /only record user-prompt changes to the reusable workflow itself/);
  assert.match(system, /Keep reusable guidance as a Memory Signal when it fits in 1-3 concise sentences/);
  assert.match(system, /do not duplicate the same guidance as both a Memory Signal and a Skill Signal/);
  assert.match(system, /Create, update, or upgrade a Skill Signal only when user prompts indicate an intent to shape a reusable workflow/);
  assert.match(system, /workflow needs at least 3 reusable steps/);
  assert.doesNotMatch(system, /Create, update, or upgrade to a Skill Signal only when user prompts explicitly ask to remember, reuse, or standardize a workflow for future tasks/);
  assert.doesNotMatch(system, /Create or update a Skill Signal only when user prompts explicitly request, correct, endorse, or ask to remember a reusable workflow/);
  assert.doesNotMatch(system, /Skill Signals must be supported by user prompts that explicitly describe, request, correct, or endorse a reusable workflow/);
  assert.match(system, /Do not create Skill Signals from task execution artifacts, assistant-devised plans, command history, or one-off task steps/);
  assert.doesNotMatch(system, /Do not create Skill Signals from assistant-devised plans, execution paths, review checklists, implementation steps, tool usage, command sequences, or successful task trajectories/);
  assert.match(system, /Store details only for accepted Skill Signals under `## Skill Details`; assistant execution may help fill reusable details only after the Skill Signal is supported by user prompts/);
  assert.doesNotMatch(system, /Assistant execution may only help write Skill Details for a Skill Signal that is already supported by user prompts/);
  assert.doesNotMatch(system, /current task trajectory as workflow context/);
  assert.match(system, /Each Skill Signal is one top-level bullet: `- \[<turn_id> \+<contribution>, \.\.\.\] Skill name: one concise reusable workflow capability\.`/);
  assert.match(system, /Write Skill names in the dominant language of the supporting user prompts/);
  assert.doesNotMatch(system, /Skill names must match `\^\[a-z0-9\]\[a-z0-9\._-\]\*\$`/);
  assert.doesNotMatch(system, /Store reusable workflow details in `## Skill Details` under the same skill name/);
  assert.doesNotMatch(system, /Create or update Skill Details only for an accepted Skill Signal/);
  assert.doesNotMatch(system, /hard-won fixes after errors\/dead ends/);
  assert.doesNotMatch(system, /Drop task plans, prompt\/spec drafts, PR chores, CI status, command logs, one-off reproduction notes, and feature-local implementation steps/);
  assert.doesNotMatch(system, /Skills: reusable workflow candidates that apply beyond one task/);
  assert.doesNotMatch(system, /A Skill top-level bullet names the reusable workflow/);
  assert.doesNotMatch(system, /nested bullets may split reusable process details into Trigger, Steps, Checks, and Output/);
  assert.doesNotMatch(system, /Open Questions/);
  assert.doesNotMatch(system, /Open Questions are unresolved decisions, blockers, or confirmations that affect future sessions beyond the current task/);
  assert.doesNotMatch(system, /Open Questions may only be created, rewritten, or strengthened by user prompts/);
  assert.match(system, /Signal evidence/);
  assert.match(system, /Signal bullets use evidence labels instead of weight markers/);
  assert.match(system, /Use `\+1` for ordinary supporting user prompts/);
  assert.match(system, /Use `\+10` when the user explicitly asks to remember or reuse the signal in future sessions/);
  assert.match(system, /Add one evidence label for each distinct current-batch turn whose user prompt supports the retained signal/);
  assert.match(system, /Do not invent turn ids or contribution values/);
  assert.match(system, /Do not duplicate the same turn id within one signal/);
  assert.doesNotMatch(system, /Signal weights/);
  assert.doesNotMatch(system, /Use `\[1\]` to `\[10\]`; cap at `\[10\]`/);
  assert.doesNotMatch(system, /Signal weights follow the same evidence rules/);
  assert.doesNotMatch(system, /Memory Signals and Open Questions: only user-prompt evidence may create, rewrite, or increase weight/);
  assert.doesNotMatch(system, /Skill Signals: qualifying reusable workflow evidence may create, rewrite, or increase weight only when it passes the Skill Signal rules above/);
  assert.doesNotMatch(system, /If the user explicitly asks to remember or reuse a Memory Signal or Skill Signal in future sessions/);
  assert.doesNotMatch(system, /Count evidence events conservatively/);
  assert.doesNotMatch(system, /Repeated task steps, command sequences, or feature-local instructions do not increase weight/);
  assert.doesNotMatch(system, /Count distinct user prompts as evidence/);
  assert.doesNotMatch(system, /Multiple mentions inside one prompt count as one evidence event/);
  assert.doesNotMatch(system, /A new signal starts with weight equal to its current-batch evidence count, capped at `\[3\]`/);
  assert.doesNotMatch(system, /An existing signal gains `\+1` per current-batch evidence event, capped at `\+3` per batch/);
  assert.doesNotMatch(system, /Assistant responses and agent application must not create Memory Signals or Open Questions, rewrite them, broaden their scope, or increase numeric weight/);
  assert.doesNotMatch(system, /Do not invent historical counts; use existing weight plus current-batch evidence/);
  assert.doesNotMatch(system, /user-backed or user-validated guidance/);
  assert.doesNotMatch(system, /Agent confirmation\/application cannot create signals/);
  assert.doesNotMatch(system, /agent visibly applies or confirms/);
  assert.doesNotMatch(system, /a later user response leaves that signal-based behavior uncorrected/);
  assert.doesNotMatch(system, /New user-supported signals start at `\[1\]`, or `\[2\]` when repeated in the current batch/);
  assert.doesNotMatch(system, /The user (?:has|repeatedly) emphasized/);
  assert.doesNotMatch(system, /`\[low\]`/);
  assert.doesNotMatch(system, /`\[medium\]`/);
  assert.doesNotMatch(system, /`\[high\]`/);
  assert.doesNotMatch(system, /`\[xhigh\]`/);
  assert.doesNotMatch(system, /Notice signals when/);
  assert.doesNotMatch(system, /Keep `## Signals` compact: usually 1-5 bullets/);
  assert.match(system, /Signal budget/);
  assert.match(system, /Overall budget/);
  assert.match(system, /`### Content` is optional/);
  assert.match(system, /Each `### Summary` is usually 32-96 tokens, with a hard maximum of 128 tokens/);
  assert.doesNotMatch(system, /These are upper bounds, not targets to fill/);
  assert.doesNotMatch(system, /These are upper-bound budgets, not targets to fill/);
  assert.match(system, /Each signal section has at most 10 top-level bullets/);
  assert.match(system, /Sort top-level bullets with explicit `\+10` evidence first, then retained evidence contribution sum, then current-batch supporting prompt count, then prior order/);
  assert.match(system, /Over budget, drop signals from the bottom of that order/);
  assert.match(
    system,
    /Each top-level signal is one concise, context-independent sentence, usually under 40 words/,
  );
  assert.match(system, /Skill Details are procedure detail space, not a transcript; keep reusable `When to Use`, `Procedure`, `Pitfalls`, and `Verification` sections concise/);
  assert.match(system, /Do not repeat the skill name as a heading inside the Skill Detail body/);
  assert.match(system, /Inside each Skill Detail body, use `#### When to Use`, `#### Procedure`, `#### Pitfalls`, and `#### Verification` for reusable detail sections/);
  assert.doesNotMatch(system, /nested Skills bullets stay concise and only cover triggers, steps, checks, or expected output/);
  assert.match(system, /`### Summary` and `### Content` share a maximum 512-token budget across all changed extraction units in one snapshot patch/);
  assert.match(system, /Extraction content rules/);
  assert.doesNotMatch(system, /Memory selection and content/);
  assert.match(system, /Use `### Summary` as the compact recall capsule for core extracted information/);
  assert.match(system, /Use `### Content` only for non-redundant retrieval anchors that would make the summary too dense/);
  assert.match(system, /If source content is valuable as a semantic retrieval index, extract and write it into the extraction/);
  assert.match(system, /Use citations to index non-core source details or exact passages without copying them into `### Content`/);
  assert.match(system, /Before each citation, write a short summary of the cited turn's relevant content/);
  assert.doesNotMatch(system, /exact evidence/);
  assert.match(system, /When one extraction would exceed budget, split by durable topic instead of adding more detail to the same extraction/);
  assert.doesNotMatch(system, /For process-heavy work such as PRs, CI, and debugging/);
  assert.doesNotMatch(system, /For long logs, code, command output, PR status, or debugging history/);
  assert.match(system, /Extraction citations/);
  assert.doesNotMatch(system, /Source evidence and citations/);
  assert.doesNotMatch(system, /## Signals\b/);
  assert.doesNotMatch(system, /Title:/);
  assert.match(system, /### Title/);
  assert.doesNotMatch(system, /Hard max/);
  assert.doesNotMatch(system, /`Concept`/);
  assert.doesNotMatch(system, /`Other`/);
  assert.doesNotMatch(system, /"category": "Goal"/);
  assert.doesNotMatch(system, /`Goal`/);
  assert.match(system, /snapshot patch/i);
  assert.match(system, /Extraction unit/);
  assert.match(system, /Existing extraction updates must start with metadata containing the existing `sequence` number and `refs`/);
  assert.match(system, /Metadata refs must only include actual supporting turn ids from the current batch/);
  assert.match(system, /Never output placeholder or copied example refs/);
  assert.doesNotMatch(system, /Remove an Open Question once it is resolved/);
  assert.doesNotMatch(system, /refs: \[turn:x/);
  assert.doesNotMatch(system, /1-3 memory anchor lines/);
  assert.doesNotMatch(system, /\[Entity\] Alex/);
  assert.doesNotMatch(system, /\[Extraction\]/);
  assert.doesNotMatch(system, /updates:/);
  assert.doesNotMatch(system, /increment its `updates` count/);
  assert.match(system, /Use the current snapshot title, summaries, signal sections, and current batch turns/);
  assert.doesNotMatch(system, /Keep the original remembered object in `\[Extraction\]`/);
  assert.doesNotMatch(system, /do not replace it with a broader summary or leave it only in `\[Context\]`/);
  assert.match(system, /preserve identifiers exactly/i);
  assert.doesNotMatch(system, /Keep the target object and key wording/);
  assert.doesNotMatch(system, /Responses, judgments, reactions, and feedback/);
  assert.match(system, /Do not include old refs/);
  assert.doesNotMatch(system, /^  \s*`\[Category/m);
  assert.doesNotMatch(system, /Refs: \[/);
  assert.doesNotMatch(system, /never remove the `Refs:` line/);
  assert.doesNotMatch(system, /Update at most 5 existing memory units/);
  assert.doesNotMatch(system, /Add at most 2 new memory units/);
  assert.doesNotMatch(system, /Do not return JSON/);
  assert.doesNotMatch(system, /"extractionChanges"/);
  assert.doesNotMatch(system, /call `memory-get`/);
  assert.doesNotMatch(system, /visible turn ids/);
  assert.doesNotMatch(system, /session snapshot details/);
  assert.doesNotMatch(system, /existing extraction details/);
  assert.doesNotMatch(system, /Id usage/);
  assert.doesNotMatch(system, /sessionMemory\.extractions/);
  assert.doesNotMatch(system, /extraction rows, or extraction ids/);
  assert.doesNotMatch(system, /"extractions": \[/);
  assert.doesNotMatch(system, /Keep unresolved conflicts in `openQuestions`/);
  assert.doesNotMatch(system, /extractionConsolidation/);
  assert.doesNotMatch(system, /extractionDelta/);
  assert.doesNotMatch(system, /sessionMemoryUpdate/);
  assert.doesNotMatch(system, /whyRelated/);
  assert.doesNotMatch(system, /memoryDelta\.before/);
  assert.doesNotMatch(system, /sourceRefs/);
  assert.doesNotMatch(system, /excerpt/);
  assert.doesNotMatch(system, /fragments/);
});

test('chat domain prompt defines subject routing boundaries', () => {
  const template = loadPromptTemplate('chat');
  const system = template.system;

  assert.match(system, /Same vs separate routing/);
  assert.match(system, /Keep spans with a subject thread when they complete or refine that subject/);
  assert.match(system, /Route spans to the session thread when they introduce a different subject/);
  assert.match(system, /do not clearly fit an existing subject thread/);
  assert.match(system, /need later derivation/);
  assert.match(system, /Do not route to a subject thread only because spans are adjacent, in the same batch, or mention the same people/);
  assert.doesNotMatch(system, /separate work item/);
  assert.doesNotMatch(system, /Split spans/);
});

test('session memory prompt uses raw turns and returns snapshot content document', () => {
  const template = loadPromptTemplate('thread_extracting');
  const system = template.system;

  assert.match(system, /current batch turns/i);
  assert.doesNotMatch(system, /newTurns/);
  assert.match(system, /get_extraction/);
  assert.match(system, /get_turn/);
  assert.match(system, /raw current-batch turn row id without a `turn:` prefix/);
  assert.match(system, /citations still use `@\[turn:<turnId>\]`/);
  assert.doesNotMatch(system, /memory-get/);
  assert.doesNotMatch(system, /memory_get/);
  assert.match(system, /Current snapshot/);
  assert.match(system, /existing extraction titles\/summaries/i);
  assert.match(system, /Return a Markdown snapshot patch, not a full snapshot/);
  assert.match(system, /Return a snapshot patch only: include only changed title, summary, signal sections, Skill Details, and changed\/new extractions/);
  assert.match(system, /do not wrap the whole response in a code fence or add prose outside the document/);
  assert.doesNotMatch(system, /one `# <session title>`/);
  assert.match(system, /Include `## Summary` only when the session summary should change/);
  assert.match(system, /Include `## Memory Signals` only when Memory Signals change/);
  assert.match(system, /an empty `## Memory Signals` clears existing Memory Signals/);
  assert.match(system, /Include `## Skill Signals` only when Skill Signals change/);
  assert.doesNotMatch(system, /Include `## Open Questions`/);
  assert.match(system, /Include `## Skill Details` only when any Skill Detail changes or should be removed/);
  assert.match(system, /Every changed Skill Detail must have a matching Skill Signal after the patch is applied/);
  assert.match(system, /Include `## Extractions` only when any extraction changes or new extraction is created/);
  assert.doesNotMatch(system, /extraction rows, or extraction ids/);
  assert.doesNotMatch(system, /contextRefs/);
  assert.doesNotMatch(system, /sourceReferences/);
  assert.match(system, /Compare current batch turns with existing extraction titles, summaries, Memory Signals, and Skill Signals before creating new extraction units or signals/);
  assert.match(system, /Do not split related content into a new extraction just to avoid calling `get_extraction`/);
  assert.match(system, /Use `get_skill` only for existing Skill Signals/);
  assert.match(system, /Do not call `get_skill` for Memory Signals/);
  assert.match(system, /Use `get_turn` only when a rendered prompt\/response preview is insufficient to safely create or update the snapshot/);
  assert.match(system, /You may call `get_turn` at most 3 times/);
  assert.match(system, /Do not include unchanged Skill Details in the output patch/);
  assert.match(system, /You may call `get_skill` at most once per skill name/);
  assert.match(system, /at most 5 times/);
  assert.doesNotMatch(system, /MUST call `get_extraction` at least once/);
  assert.doesNotMatch(system, /Extraction Index/);
  assert.match(system, /Example input/);
  assert.match(system, /Example input\n----------------/);
  assert.match(system, /Example output/);
  assert.match(system, /Example output\n-----------------/);
  assert.match(system, /Example output\n-----------------\n# Report export defaults\n\n## Summary\n\nThis session refined report export defaults/);
  assert.doesNotMatch(system, /## Memory Signals\n\n- \[2\] Report export filenames should include project name, environment name, and export date\./);
  assert.doesNotMatch(system, /## Memory Signals[\s\S]*Report exports should default to CSV unless the user explicitly asks for another format/);
  assert.match(system, /- \[turn:102 \+1\] Report export failures should be triaged by checking job logs before object storage permissions\./);
  assert.doesNotMatch(system, /## Skill Signals\n\n- \[1\] `report-export-triage`: Triage report export failures by checking job logs before object storage permissions\./);
  assert.doesNotMatch(system, /## Open Questions/);
  assert.match(system, /Report export audit field/);
  assert.match(system, /Report export audit field naming is unresolved; current candidates are `requested_by` and `requestedBy`/);
  assert.doesNotMatch(system, /## Skill Details\n\n### `report-export-triage`/);
  assert.doesNotMatch(system, /# report-export-triage/);
  assert.doesNotMatch(system, /#### When to Use\nUse when report export jobs fail\./);
  assert.doesNotMatch(system, /#### Procedure\n- Check job logs before object storage permissions\./);
  assert.doesNotMatch(system, /#### Pitfalls\n- Do not preserve temporary project names as reusable rules\./);
  assert.doesNotMatch(system, /#### Verification\n- Keep the final root cause and fix, not every inspection step\./);
  assert.match(system, /demo-42/);
  assert.match(system, /add debug logs, rerun CI once, and summarize PR status/);
  const exampleOutput = system.split('Example output\n-----------------\n')[1] ?? '';
  assert.doesNotMatch(exampleOutput, /demo-42/);
  assert.doesNotMatch(exampleOutput, /debug logs|rerun CI|PR status/);
  assert.match(system, /## Current Snapshot/);
  assert.match(system, /# Report export defaults/);
  assert.doesNotMatch(system, /# 报表导出默认设置/);
  assert.match(system, /## Current Batch Turns/);
  assert.match(system, /Prompt \(user evidence\):/);
  assert.match(system, /Response \(context, not signal evidence\):/);
  assert.doesNotMatch(system, /Prompt \(memory signal evidence\):/);
  assert.doesNotMatch(system, /Response \(workflow context, not memory signal evidence\):/);
  assert.match(system, /<!-- sequence: 0 -->/);
  assert.match(system, /<!-- sequence: 0; refs: \[turn:102\] -->/);
  assert.doesNotMatch(system, /Muninn extractor/);
  assert.doesNotMatch(system, /partial Markdown snapshot patch 更新已有 memory unit/);
  assert.doesNotMatch(system, /sourceRefs/);
  assert.doesNotMatch(system, /excerpt/);
  assert.doesNotMatch(system, /fragments/);
  assert.doesNotMatch(system, /DATE:/);
  assert.doesNotMatch(system, /Incidental media/i);
  assert.doesNotMatch(system, /Do not turn .*liked.*reacted.*image.*painting.* into .*Fact/i);
  assert.doesNotMatch(system, /`summary`: grounded content from the turn/);
});

test('project dreamer prompt merges incremental project signals without session refs', () => {
  const template = loadPromptTemplate('project_dreaming');
  const system = template.system;
  assert.match(system, /project signal merge agent/i);
  assert.match(system, /Maintain the current project signal set/);
  assert.match(system, /Merge existing project signals with incremental session signal evidence/);
  assert.match(system, /Return a complete Markdown project signal set, not a patch/);
  assert.match(system, /Existing project signal rows, each labeled with `\[signal:<stable_row_id>\]`/);
  assert.match(system, /Incremental session Memory Signals and Skill Signals, each labeled with one or more `\[<turn_id> \+<contribution>\]` evidence labels/);
  assert.match(system, /Existing project signal labels identify stored rows; incremental turn labels identify user-prompt evidence/);
  assert.match(system, /Existing `\[signal:\*\]` labels are row identities, not evidence/);
  assert.match(system, /Incremental full-turn-id labels are new evidence/);
  assert.doesNotMatch(system, /lightweight signal/i);
  assert.doesNotMatch(system, /Tool use/);
  assert.doesNotMatch(system, /get_skill/);
  assert.match(system, /Preserve source-supported meaning, scope, constraints, and signal type/);
  assert.match(system, /Merge or update semantically related signals using incremental wording as the latest state/);
  assert.match(system, /include incremental turn labels only when they support the final wording and scope/);
  assert.match(system, /Do not broaden, invent, or reclassify signals/);
  assert.match(system, /Avoid duplicating the same reusable guidance as both a Memory Signal and a Skill Signal/);
  assert.match(system, /For Skill Signals, merge details when source Skill Signal content supports the same reusable workflow/);
  assert.match(system, /Sources are ordered older to newer; later evidence can replace earlier overlapping content/);
  assert.match(system, /Write direct future-agent instructions in the dominant language of retained source signals/);
  assert.match(system, /preserve identifiers exactly/);
  assert.match(system, /Memory Signals are concise future-agent operating instructions/);
  assert.match(system, /Skill Signals are reusable workflow entries with a skill name, short summary, and optional reusable details/);
  assert.doesNotMatch(system, /Open Questions:/);
  assert.doesNotMatch(system, /Signal weights/);
  assert.doesNotMatch(system, /Do not cap weights at a fixed maximum/);
  assert.doesNotMatch(system, /Budget/);
  assert.match(system, /Output labels drive deterministic storage upserts/);
  assert.match(system, /Every output signal block must start with exactly one label list/);
  assert.match(system, /Use only labels that appeared in the input/);
  assert.match(system, /\[signal:<stable_row_id>\]` labels identify existing project rows/);
  assert.match(system, /\[<turn_id> \+<contribution>\]` labels identify incremental evidence/);
  assert.match(system, /the first `\[signal:\*\]` is the survivor row/);
  assert.match(system, /Additional `\[signal:\*\]` labels in the same output block are merged into the survivor row and removed from current state/);
  assert.match(system, /If an output block has only turn evidence labels, it creates a new project signal row/);
  assert.match(system, /If an input `\[signal:\*\]` label is omitted from the output, that existing project signal is removed from current state/);
  assert.doesNotMatch(system, /session:<rowid>/);
  assert.doesNotMatch(system, /\(refs:/);
  assert.match(system, /Start with `# Project Signals`/);
  assert.match(system, /Every saved signal content block starts with either `## Memory Signal` or `## Skill Signal`/);
  assert.match(system, /Skill Signal content starts with `## Skill Signal`, then `### <skill name>`/);
  assert.doesNotMatch(system, /# Project Dream: \{\{project\}\}/);
  assert.doesNotMatch(system, /\[N\]/);
  assert.doesNotMatch(system, /Include `## Signals`/);
  assert.doesNotMatch(system, /Include `### Guidance`, `### Skills`, and `### Open Questions`/);
  assert.match(template.userTemplate, /## Existing Project Signals/);
  assert.match(template.userTemplate, /## Incremental Session Signals/);
  assert.doesNotMatch(template.userTemplate, /## Parent Dream/);
  assert.doesNotMatch(template.userTemplate, /## Incremental Signals/);
  assert.doesNotMatch(template.userTemplate, /## Incremental Lightweight Signals/);
  assert.doesNotMatch(template.userTemplate, /### session:/);
});
