import test from 'node:test';
import assert from 'node:assert/strict';

import { loadPromptTemplate } from '../../dist/llm/prompts.js';

test('memory recaller prompt composes recall context with a soft budget', () => {
  const prompt = loadPromptTemplate('memory_recaller');

  assert.match(prompt.system, /memory recall agent/i);
  assert.match(prompt.system, /different agents, sessions, and contexts/i);
  assert.match(prompt.system, /integrate the relevant memories/i);
  assert.match(prompt.system, /filter out unrelated content/i);
  assert.match(prompt.system, /main agent should see/i);
  assert.match(prompt.system, /identify the query intent/i);
  assert.match(prompt.system, /General rules/);
  assert.match(prompt.system, /Do not answer the query/);
  assert.match(prompt.system, /Prepare memory for the main agent/);
  assert.match(prompt.system, /Do not compute, finalize, or decide the answer/);
  assert.match(prompt.system, /especially time expressions/);
  assert.match(prompt.system, /compress context that is not useful or unrelated to the query/);
  assert.match(prompt.system, /Do not invent facts or make inferences/);
  assert.match(prompt.system, /candidate memories conflict/);
  assert.match(prompt.system, /soft target/);
  assert.match(prompt.system, /preserve relevant memory details and accuracy/);
  assert.match(prompt.system, /Factual recall/);
  assert.match(prompt.system, /Judgment recall/);
  assert.match(prompt.system, /gather directly relevant facts around the query/);
  assert.match(prompt.system, /Keep concrete values and relevant context/);
  assert.match(prompt.system, /compatible parts from multiple candidates/);
  assert.match(prompt.system, /keep distinct subjects, events, times, or conditions separate/);
  assert.match(prompt.system, /Do not replace concrete facts with uncertainty/);
  assert.match(prompt.system, /judgment, match, preference, likelihood, comparison, or inference based on memory/);
  assert.match(prompt.system, /positive and negative memory signals and details/);
  assert.match(prompt.system, /limits, uncertainty, or mismatches/);
  assert.match(prompt.system, /Do not answer the judgment/);
  assert.match(prompt.userTemplate, /Budget:/);
  assert.doesNotMatch(prompt.userTemplate, /General rules/);
  assert.doesNotMatch(prompt.userTemplate, /Factual recall/);
  assert.match(prompt.userTemplate, /Return refs for the memory candidates used to write the content/);
  assert.match(prompt.userTemplate, /Return JSON only/);
  assert.match(prompt.userTemplate, /"refs"/);
});

test('thread session memory prompt organizes entity extractions by questions', () => {
  const prompt = loadPromptTemplate('thread_observing');

  assert.match(prompt.system, /observer that maintains parts of a cross-extraction tree/i);
  assert.match(prompt.system, /observed_document: a view of the observation tree/i);
  assert.match(prompt.system, /new or changed memory fragments to integrate/i);
  assert.match(prompt.system, /observed_document is only this job's view/);
  assert.match(prompt.system, /Use both Context and Extraction as source material/);
  assert.match(prompt.system, /Headings without body content are navigation only/i);
  assert.match(prompt.system, /get_observation\(paths\)/);
  assert.match(prompt.system, /batch related paths in each call and copy path strings exactly from heading `path:` comments/);
  assert.match(prompt.system, /Section, leaf, and source budget/);
  assert.match(prompt.system, /Use headings up to `####` only/);
  assert.match(prompt.system, /usually 100-500 words with 1-5 source extractions/);
  assert.match(prompt.system, /keep exact dates, places, names, source objects, and concrete labels in the body/);
  assert.match(prompt.system, /use `Source extractions:` for source-level detail below it/);
  assert.match(prompt.system, /split into narrower sibling leaves/);
  assert.match(prompt.system, /promote a broad scope into child leaves/);
  assert.doesNotMatch(prompt.system, /will be expanded during future recall/);
  assert.doesNotMatch(prompt.system, /under 2000 tokens/);
  assert.doesNotMatch(prompt.system, /naturally needs nested leaf headings/);
  assert.match(prompt.system, /Observation rewrite rules/);
  assert.match(prompt.system, /Source extractions:/);
  assert.match(prompt.system, /Single-source bullet format is exactly/);
  assert.match(prompt.system, /no text may follow it/);
  assert.match(prompt.system, /Use a multi-source bullet only when multiple source extractions are merged/);
  assert.match(prompt.system, /content is required and must preserve source-level detail and wording/);
  assert.match(prompt.system, /Heading-only sections mean unchanged: output only the heading line/);
  assert.match(prompt.system, /headings visible in the observed_document or tool results/);
  assert.match(prompt.system, /Do not output `path:` comments/);
  assert.doesNotMatch(prompt.system, /observation ids/i);
  assert.doesNotMatch(prompt.system, /delete: true/);
  assert.doesNotMatch(prompt.system, /<!-- id:/);
  assert.doesNotMatch(prompt.system, /memory-get/);
  assert.doesNotMatch(prompt.userTemplate, /Root anchor:/);
  assert.doesNotMatch(prompt.userTemplate, /Rewrite content:/);
  assert.doesNotMatch(prompt.userTemplate, /Observation outline:/);
  assert.match(prompt.userTemplate, /Observed document:/);
  assert.match(prompt.userTemplate, /Extraction units:/);
});

test('chat domain prompt provides category guidance without session memory workflow schema', () => {
  const template = loadPromptTemplate('chat');
  const system = template.system;

  assert.match(system, /Chat memory categories/);
  assert.match(system, /Session memory thread definition/);
  assert.match(system, /subject session memory thread tracks one coherent subject that can develop over time/);
  assert.match(system, /narrower than the whole conversation and more stable than a single message/);
  assert.match(system, /Route a new span to a subject thread only when it updates, answers, clarifies, corrects, supports, or directly continues that subject/);
  assert.doesNotMatch(system, /Use `update` plus `add`/);
  assert.doesNotMatch(system, /Chat filtering/);
  assert.doesNotMatch(system, /Extraction granularity/);
  assert.match(system, /Use categories only to organize snapshot content/);
  assert.match(system, /First write the memory content, then choose one or more categories/);
  assert.match(system, /Store useful conclusions, answers, states, plans, preferences, or reusable facts, not conversation acts/);
  assert.match(system, /Fold chat evidence into the relevant existing context/);
  assert.doesNotMatch(system, /greetings, small talk, filler/);
  assert.doesNotMatch(system, /pure questions, temporary status updates/);
  assert.doesNotMatch(system, /descriptive details, transition remarks, pure questions, one-off actions/);
  assert.match(system, /stable or recurring like/);
  assert.match(system, /explicit, non-trivial, and useful beyond the current conversation/);
  assert.doesNotMatch(system, /Prefer `Fact` for one-time events, described objects, and answerable details/);
  assert.doesNotMatch(system, /Prefer `Decision` when the main signal is what someone plans, chooses, or commits to do/);
  assert.doesNotMatch(system, /Prefer `Preference` only when the signal is stable or recurring/);
  assert.doesNotMatch(system, /Prefer `Entity` only for stable attributes, not one-time events involving the entity/);
  assert.match(system, /When chat memory contains a time expression/);
  assert.match(system, /normalize it to absolute time using grounded context anchors when possible/);
  assert.doesNotMatch(system, /Extract useful absolute time from context when available/);
  assert.doesNotMatch(system, /memory-get/);
  assert.doesNotMatch(system, /If an extraction or `contextRefs\.summary` would still contain unresolved relative time/);
  assert.match(system, /useful memory that does not fit above/);
  assert.doesNotMatch(system, /Extraction definition/);
  assert.doesNotMatch(system, /Thread title/);
  assert.doesNotMatch(system, /Thread summary/);
  assert.doesNotMatch(system, /memory_get/);
  assert.doesNotMatch(system, /extractionChanges/);
  assert.doesNotMatch(system, /extractionDelta/);
  assert.doesNotMatch(system, /Return exactly one JSON object/);
});

test('thread session memory prompt uses generic recall-ready memory guidance', () => {
  const template = loadPromptTemplate('thread_extracting');
  const system = template.system;

  assert.doesNotMatch(system, /Extraction state: the complete current list of extractions this thread should keep/);
  assert.match(system, /Memory unit rules/);
  assert.match(system, /organizes related session content for future recall/);
  assert.match(system, /durable topic: a decision, requirement, preference, correction, finding, problem, solution, risk, task state, or open question/);
  assert.match(system, /Merge repeated corrections or refinements of the same topic/);
  assert.match(system, /Split a unit when its Content needs to grow beyond budget/);
  assert.match(system, /extractor that updates a session memory snapshot from new conversation turns/);
  assert.match(system, /Use the current snapshot title, summaries, and current batch turns/);
  assert.doesNotMatch(system, /existingSnapshotContent/);
  assert.match(system, /Return a Markdown snapshot patch, not a full snapshot/);
  assert.match(system, /# <Session Title>/);
  assert.match(system, /### Title/);
  assert.match(system, /Session title target: 4-8 tokens/);
  assert.match(system, /Extraction title target: 4-24 tokens/);
  assert.match(system, /## Summary/);
  assert.match(system, /## Extractions/);
  assert.doesNotMatch(system, /Routing has already selected the fragments for this thread/);
  assert.doesNotMatch(system, /routed fragments/);
  assert.doesNotMatch(system, /Fragment:/);
  assert.doesNotMatch(system, /rewrite clear relative dates or periods into absolute dates or periods/);
  assert.doesNotMatch(system, /`yesterday`, `tomorrow`, `last week`, `last month`, and `last year`/);
  assert.doesNotMatch(system, /Fallback inspection/);
  assert.doesNotMatch(system, /batches of up to 5/);
  assert.doesNotMatch(system, /starting from the first sourceRef/);
  assert.match(system, /Filter greetings, acknowledgements, filler, and pure transcript mechanics/);
  assert.match(system, /Create or update a unit for a durable topic/);
  assert.doesNotMatch(system, /Remove or rewrite units that are outdated, wrong, or duplicated/);
  assert.doesNotMatch(system, /When normalizing a time expression/);
  assert.doesNotMatch(system, /Keep the original remembered object in `\[Extraction\]`/);
  assert.doesNotMatch(system, /do not replace it with a broader summary or leave it only in `\[Context\]`/);
  assert.match(system, /store facts, decisions, constraints, and current state/);
  assert.match(system, /Do not retell the conversation step by step/);
  assert.doesNotMatch(system, /can be remembered content when they describe something specific/);
  assert.doesNotMatch(system, /Granularity:/);
  assert.doesNotMatch(system, /memory unit purpose/);
  assert.doesNotMatch(system, /Memory anchors/);
  assert.doesNotMatch(system, /1-3 memory anchors/);
  assert.doesNotMatch(system, /Anchor names/);
  assert.doesNotMatch(system, /Memory categories/);
  assert.doesNotMatch(system, /Domain guidance/);
  assert.doesNotMatch(system, /domain_prompt/);
  assert.doesNotMatch(system, /Category selection:/);
  assert.doesNotMatch(system, /Prefer the most specific category over `Fact` when an extraction describes/);
  assert.doesNotMatch(system, /Extraction definition/);
  assert.doesNotMatch(system, /Recall-ready writing/);
  assert.doesNotMatch(system, /Derivation style/);
  assert.doesNotMatch(system, /Fact quality/);
  assert.match(system, /Session title target/);
  assert.match(system, /Titles are UI labels/);
  assert.doesNotMatch(system, /key person\/entity\/object plus concrete topic, activity, artifact, plan, relationship, or state/);
  assert.doesNotMatch(system, /stable thread subject, not the latest turn/);
  assert.doesNotMatch(system, /stay neutral and concrete without overstating long-term meaning/);
  assert.doesNotMatch(system, /meta labels/);
  assert.doesNotMatch(system, /Prefer 6-14 words/);
  assert.match(system, /4-8 tokens/);
  assert.match(system, /Summary/);
  assert.doesNotMatch(system, /Thread state/);
  assert.doesNotMatch(system, /contextRefs/);
  assert.doesNotMatch(system, /snapshotContent/);
  assert.doesNotMatch(system, /Include a `contextRef` for every new turn whose information is used/);
  assert.doesNotMatch(system, /clarifies ownership, time, attribution, or status/);
  assert.doesNotMatch(system, /openQuestions/);
  assert.doesNotMatch(system, /nextSteps/);
  assert.doesNotMatch(system, /roughly 1000 characters/);
  assert.doesNotMatch(system, /roughly 500 characters/);
});

test('session memory prompt preserves the current extraction schema', () => {
  const template = loadPromptTemplate('thread_extracting');
  const system = template.system;

  assert.match(system, /Each extraction must include `### Title` and `### Summary`/);
  assert.match(system, /Always maintain `## Signals` after `## Summary`/);
  assert.match(system, /Notice signals when/);
  assert.match(system, /The user corrects the agent, repeats a requirement, or says something should be remembered or avoided next time/);
  assert.match(system, /durable preference, habit, communication style, review style, or decision standard/);
  assert.match(system, /project convention, environment detail, tool quirk, API quirk, or recurring workflow/);
  assert.match(system, /reusable procedure, debugging path, prompt rule, or skill-worthy workflow/);
  assert.match(system, /Preserve existing signals that are still valid/);
  assert.match(system, /Remove a signal only when it is resolved, superseded, contradicted, or no longer useful for future recall/);
  assert.match(system, /Merge related new evidence into an existing bullet instead of appending a turn-by-turn log/);
  assert.match(system, /`### Content` is optional/);
  assert.match(system, /Extraction summary target: 64-128 tokens/);
  assert.match(system, /Extraction content target: 512-1024 tokens when content is needed/);
  assert.match(system, /Use `### Content` for structured details/);
  assert.doesNotMatch(system, /Signals:/);
  assert.doesNotMatch(system, /Title:/);
  assert.match(system, /### Title/);
  assert.doesNotMatch(system, /Hard max/);
  assert.doesNotMatch(system, /`Concept`/);
  assert.doesNotMatch(system, /`Other`/);
  assert.doesNotMatch(system, /"category": "Goal"/);
  assert.doesNotMatch(system, /`Goal`/);
  assert.match(system, /snapshot patch/i);
  assert.match(system, /Memory unit/);
  assert.match(system, /Existing extraction updates must start with metadata containing the existing `sequence` number and `refs`/);
  assert.match(system, /Metadata refs must only include actual supporting turn ids from the current batch/);
  assert.match(system, /Never output placeholder or copied example refs/);
  assert.match(system, /A decision remains unresolved and would change future work; remove it once it is answered or no longer blocks future work/);
  assert.doesNotMatch(system, /refs: \[turn:x/);
  assert.doesNotMatch(system, /1-3 memory anchor lines/);
  assert.doesNotMatch(system, /\[Entity\] Alex/);
  assert.doesNotMatch(system, /\[Extraction\]/);
  assert.doesNotMatch(system, /updates:/);
  assert.doesNotMatch(system, /increment its `updates` count/);
  assert.match(system, /Use the current snapshot title, summaries, and current batch turns/);
  assert.doesNotMatch(system, /Keep the original remembered object in `\[Extraction\]`/);
  assert.doesNotMatch(system, /do not replace it with a broader summary or leave it only in `\[Context\]`/);
  assert.match(system, /preserve code and project identifiers/i);
  assert.doesNotMatch(system, /Keep the target object and key wording/);
  assert.doesNotMatch(system, /Responses, judgments, reactions, and feedback/);
  assert.match(system, /Do not include old refs/);
  assert.doesNotMatch(system, /^  \s*`\[Category/m);
  assert.doesNotMatch(system, /Refs: \[/);
  assert.doesNotMatch(system, /never remove the `Refs:` line/);
  assert.doesNotMatch(system, /Update at most 5 existing memory units/);
  assert.doesNotMatch(system, /Add at most 2 new memory units/);
  assert.doesNotMatch(system, /Do not return JSON/);
  assert.doesNotMatch(system, /"extractionChanges"/);
  assert.doesNotMatch(system, /call `memory-get`/);
  assert.doesNotMatch(system, /visible turn ids/);
  assert.doesNotMatch(system, /session snapshot details/);
  assert.doesNotMatch(system, /existing extraction details/);
  assert.doesNotMatch(system, /Id usage/);
  assert.doesNotMatch(system, /sessionMemory\.extractions/);
  assert.doesNotMatch(system, /extraction rows, or extraction ids/);
  assert.doesNotMatch(system, /"extractions": \[/);
  assert.doesNotMatch(system, /Keep unresolved conflicts in `openQuestions`/);
  assert.doesNotMatch(system, /extractionConsolidation/);
  assert.doesNotMatch(system, /extractionDelta/);
  assert.doesNotMatch(system, /sessionMemoryUpdate/);
  assert.doesNotMatch(system, /whyRelated/);
  assert.doesNotMatch(system, /memoryDelta\.before/);
  assert.doesNotMatch(system, /sourceRefs/);
  assert.doesNotMatch(system, /excerpt/);
  assert.doesNotMatch(system, /fragments/);
});

test('chat domain prompt defines subject routing boundaries', () => {
  const template = loadPromptTemplate('chat');
  const system = template.system;

  assert.match(system, /Same vs separate routing/);
  assert.match(system, /Keep spans with a subject thread when they complete or refine that subject/);
  assert.match(system, /Route spans to the session thread when they introduce a different subject/);
  assert.match(system, /do not clearly fit an existing subject thread/);
  assert.match(system, /need later derivation/);
  assert.match(system, /Do not route to a subject thread only because spans are adjacent, in the same batch, or mention the same people/);
  assert.doesNotMatch(system, /separate work item/);
  assert.doesNotMatch(system, /Split spans/);
});

test('session memory prompt uses raw turns and returns snapshot content document', () => {
  const template = loadPromptTemplate('thread_extracting');
  const system = template.system;

  assert.match(system, /current batch turns/i);
  assert.doesNotMatch(system, /newTurns/);
  assert.match(system, /get_extraction/);
  assert.doesNotMatch(system, /memory-get/);
  assert.doesNotMatch(system, /memory_get/);
  assert.match(system, /Current snapshot/);
  assert.match(system, /existing extraction titles\/summaries/i);
  assert.match(system, /Return a Markdown snapshot patch, not a full snapshot/);
  assert.match(system, /do not wrap the whole response in a code fence or add prose outside the document/);
  assert.doesNotMatch(system, /one `# <session title>`/);
  assert.match(system, /Include `## Summary` only when the session summary should change/);
  assert.match(system, /Include `## Signals` only when session signals should change/);
  assert.match(system, /Include `## Extractions` only when any extraction changes or new extraction is created/);
  assert.doesNotMatch(system, /extraction rows, or extraction ids/);
  assert.doesNotMatch(system, /contextRefs/);
  assert.doesNotMatch(system, /sourceReferences/);
  assert.match(system, /Compare current batch turns with existing extraction titles and summaries/);
  assert.match(system, /Do not split related content into a new extraction just to avoid calling `get_extraction`/);
  assert.match(system, /at most 5 times/);
  assert.doesNotMatch(system, /MUST call `get_extraction` at least once/);
  assert.doesNotMatch(system, /Extraction Index/);
  assert.match(system, /Example input/);
  assert.match(system, /Example input\n----------------/);
  assert.match(system, /Example output/);
  assert.match(system, /Example output\n-----------------/);
  assert.match(system, /Example output\n-----------------\n# 报表导出默认设置\n\n## Summary\n\n本会话继续收敛报表导出功能/);
  assert.match(system, /## Signals\n\n- Repeated requirement:/);
  assert.match(system, /## Current Snapshot/);
  assert.match(system, /# 报表导出默认设置/);
  assert.doesNotMatch(system, /# Report export defaults/);
  assert.match(system, /## Current Batch Turns/);
  assert.match(system, /<!-- sequence: 0 -->/);
  assert.match(system, /<!-- sequence: 0; refs: \[turn:102\] -->/);
  assert.doesNotMatch(system, /Muninn extractor/);
  assert.doesNotMatch(system, /partial Markdown snapshot patch 更新已有 memory unit/);
  assert.doesNotMatch(system, /sourceRefs/);
  assert.doesNotMatch(system, /excerpt/);
  assert.doesNotMatch(system, /fragments/);
  assert.doesNotMatch(system, /DATE:/);
  assert.doesNotMatch(system, /Incidental media/i);
  assert.doesNotMatch(system, /Do not turn .*liked.*reacted.*image.*painting.* into .*Fact/i);
  assert.doesNotMatch(system, /`summary`: grounded content from the turn/);
});
