import test from 'node:test';
import assert from 'node:assert/strict';

import { loadPromptTemplate } from '../../dist/llm/prompts.js';

test('memory recaller prompt composes recall context with a soft budget', () => {
  const prompt = loadPromptTemplate('memory_recaller');

  assert.match(prompt.system, /memory recall agent/i);
  assert.match(prompt.system, /different agents, sessions, and contexts/i);
  assert.match(prompt.system, /integrate the relevant memories/i);
  assert.match(prompt.system, /filter out unrelated content/i);
  assert.match(prompt.system, /main agent should see/i);
  assert.match(prompt.system, /identify the query intent/i);
  assert.match(prompt.system, /General rules/);
  assert.match(prompt.system, /Do not answer the query/);
  assert.match(prompt.system, /Prepare memory for the main agent/);
  assert.match(prompt.system, /Do not compute, finalize, or decide the answer/);
  assert.match(prompt.system, /especially time expressions/);
  assert.match(prompt.system, /compress context that is not useful or unrelated to the query/);
  assert.match(prompt.system, /Do not invent facts or make inferences/);
  assert.match(prompt.system, /candidate memories conflict/);
  assert.match(prompt.system, /soft target/);
  assert.match(prompt.system, /preserve relevant memory details and accuracy/);
  assert.match(prompt.system, /Factual recall/);
  assert.match(prompt.system, /Judgment recall/);
  assert.match(prompt.system, /gather directly relevant facts around the query/);
  assert.match(prompt.system, /Keep concrete values and relevant context/);
  assert.match(prompt.system, /compatible parts from multiple candidates/);
  assert.match(prompt.system, /keep distinct subjects, events, times, or conditions separate/);
  assert.match(prompt.system, /Do not replace concrete facts with uncertainty/);
  assert.match(prompt.system, /judgment, match, preference, likelihood, comparison, or inference based on memory/);
  assert.match(prompt.system, /positive and negative instruction signals and details/);
  assert.match(prompt.system, /limits, uncertainty, or mismatches/);
  assert.match(prompt.system, /Do not answer the judgment/);
  assert.match(prompt.userTemplate, /Budget:/);
  assert.doesNotMatch(prompt.userTemplate, /General rules/);
  assert.doesNotMatch(prompt.userTemplate, /Factual recall/);
  assert.match(prompt.userTemplate, /Return refs for the memory candidates used to write the content/);
  assert.match(prompt.userTemplate, /Return JSON only/);
  assert.match(prompt.userTemplate, /"refs"/);
});

test('chat domain prompt provides category guidance without session memory workflow schema', () => {
  const template = loadPromptTemplate('chat');
  const system = template.system;

  assert.match(system, /Chat memory categories/);
  assert.match(system, /Session memory thread definition/);
  assert.match(system, /subject session memory thread tracks one coherent subject that can develop over time/);
  assert.match(system, /narrower than the whole conversation and more stable than a single message/);
  assert.match(system, /Route a new span to a subject thread only when it updates, answers, clarifies, corrects, supports, or directly continues that subject/);
  assert.doesNotMatch(system, /Use `update` plus `add`/);
  assert.doesNotMatch(system, /Chat filtering/);
  assert.doesNotMatch(system, /Extraction granularity/);
  assert.match(system, /Use categories only to organize snapshot content/);
  assert.match(system, /First write the memory content, then choose one or more categories/);
  assert.match(system, /Store useful conclusions, answers, states, plans, preferences, or reusable facts, not conversation acts/);
  assert.match(system, /Fold chat evidence into the relevant existing context/);
  assert.doesNotMatch(system, /greetings, small talk, filler/);
  assert.doesNotMatch(system, /pure questions, temporary status updates/);
  assert.doesNotMatch(system, /descriptive details, transition remarks, pure questions, one-off actions/);
  assert.match(system, /stable or recurring like/);
  assert.match(system, /explicit, non-trivial, and useful beyond the current conversation/);
  assert.doesNotMatch(system, /Prefer `Fact` for one-time events, described objects, and answerable details/);
  assert.doesNotMatch(system, /Prefer `Decision` when the main signal is what someone plans, chooses, or commits to do/);
  assert.doesNotMatch(system, /Prefer `Preference` only when the signal is stable or recurring/);
  assert.doesNotMatch(system, /Prefer `Entity` only for stable attributes, not one-time events involving the entity/);
  assert.match(system, /When chat memory contains a time expression/);
  assert.match(system, /normalize it to absolute time using grounded context anchors when possible/);
  assert.doesNotMatch(system, /Extract useful absolute time from context when available/);
  assert.doesNotMatch(system, /memory-get/);
  assert.doesNotMatch(system, /If an extraction or `contextRefs\.summary` would still contain unresolved relative time/);
  assert.match(system, /useful memory that does not fit above/);
  assert.doesNotMatch(system, /Extraction definition/);
  assert.doesNotMatch(system, /Thread title/);
  assert.doesNotMatch(system, /Thread summary/);
  assert.doesNotMatch(system, /memory_get/);
  assert.doesNotMatch(system, /extractionChanges/);
  assert.doesNotMatch(system, /extractionDelta/);
  assert.doesNotMatch(system, /Return exactly one JSON object/);
});

test('thread session memory prompt uses generic recall-ready memory guidance', () => {
  const template = loadPromptTemplate('thread_extracting');
  const system = template.system;

  assert.doesNotMatch(system, /Extraction state: the complete current list of extractions this thread should keep/);
  assert.doesNotMatch(system, /Snapshot sections/);
  assert.match(system, /## Extraction/);
  assert.match(system, /Extractions are self-contained semantic context units for future recall and later updates/);
  assert.match(system, /### Extraction rewrite rules/);
  assert.match(system, /Create or update extraction units for durable context: decisions, requirements, preferences, corrections, findings, problems, solutions, risks, task state, or open questions/);
  assert.match(system, /merge repeated corrections or refinements into the same unit/);
  assert.match(system, /Split only when a unit would exceed budget and the new content can stand as an independent durable context unit/);
  assert.match(system, /## Signal/);
  assert.match(system, /Instruction Signals are AGENTS\.md\/MEMORY\.md-style future-agent instructions/);
  assert.match(system, /Skill Signals index reusable workflow candidates that may become `SKILL\.md`; Skill Details store procedure details for accepted Skill Signals/);
  assert.match(system, /### Signal rewrite rules/);
  assert.doesNotMatch(system, /organizes related session content for future recall/);
  assert.match(system, /You update a compact session context snapshot from new conversation turns for future recall/);
  assert.doesNotMatch(system, /existingSnapshotContent/);
  assert.match(system, /Return only a Markdown snapshot patch, not a full snapshot/);
  assert.match(system, /# <Session Title>/);
  assert.match(system, /### Title/);
  assert.match(system, /Session title: usually 4-8 tokens/);
  assert.match(system, /Extraction titles are UI labels: usually 3-10 words, hard max 16 words/);
  assert.match(system, /## Summary/);
  assert.match(system, /## Extractions/);
  assert.doesNotMatch(system, /Routing has already selected the fragments for this thread/);
  assert.doesNotMatch(system, /routed fragments/);
  assert.doesNotMatch(system, /Fragment:/);
  assert.doesNotMatch(system, /rewrite clear relative dates or periods into absolute dates or periods/);
  assert.doesNotMatch(system, /`yesterday`, `tomorrow`, `last week`, `last month`, and `last year`/);
  assert.doesNotMatch(system, /Fallback inspection/);
  assert.doesNotMatch(system, /batches of up to 5/);
  assert.doesNotMatch(system, /starting from the first sourceRef/);
  assert.match(system, /Keep content dense and retrieval-oriented; avoid transcript-like detail unless it changes durable context/);
  assert.doesNotMatch(system, /Remove or rewrite units that are outdated, wrong, or duplicated/);
  assert.doesNotMatch(system, /When normalizing a time expression/);
  assert.doesNotMatch(system, /Keep the original remembered object in `\[Extraction\]`/);
  assert.doesNotMatch(system, /do not replace it with a broader summary or leave it only in `\[Context\]`/);
  assert.match(system, /Treat each extraction as a semantic retrieval unit/);
  assert.match(system, /Keep content dense and retrieval-oriented/);
  assert.doesNotMatch(system, /can be remembered content when they describe something specific/);
  assert.doesNotMatch(system, /Granularity:/);
  assert.doesNotMatch(system, /memory unit purpose/);
  assert.doesNotMatch(system, /Memory anchors/);
  assert.doesNotMatch(system, /1-3 memory anchors/);
  assert.doesNotMatch(system, /Anchor names/);
  assert.doesNotMatch(system, /Memory categories/);
  assert.doesNotMatch(system, /Domain guidance/);
  assert.doesNotMatch(system, /domain_prompt/);
  assert.doesNotMatch(system, /Category selection:/);
  assert.doesNotMatch(system, /Prefer the most specific category over `Fact` when an extraction describes/);
  assert.doesNotMatch(system, /Extraction definition/);
  assert.doesNotMatch(system, /Recall-ready writing/);
  assert.doesNotMatch(system, /Derivation style/);
  assert.doesNotMatch(system, /Fact quality/);
  assert.match(system, /Session title:/);
  assert.match(system, /Extraction titles are UI labels/);
  assert.doesNotMatch(system, /key person\/entity\/object plus concrete topic, activity, artifact, plan, relationship, or state/);
  assert.doesNotMatch(system, /stable thread subject, not the latest turn/);
  assert.doesNotMatch(system, /stay neutral and concrete without overstating long-term meaning/);
  assert.doesNotMatch(system, /meta labels/);
  assert.doesNotMatch(system, /Prefer 6-14 words/);
  assert.match(system, /4-8 tokens/);
  assert.match(system, /Summary/);
  assert.doesNotMatch(system, /Thread state/);
  assert.doesNotMatch(system, /contextRefs/);
  assert.doesNotMatch(system, /snapshotContent/);
  assert.doesNotMatch(system, /Include a `contextRef` for every new turn whose information is used/);
  assert.doesNotMatch(system, /clarifies ownership, time, attribution, or status/);
  assert.doesNotMatch(system, /openQuestions/);
  assert.doesNotMatch(system, /nextSteps/);
  assert.doesNotMatch(system, /roughly 1000 characters/);
  assert.doesNotMatch(system, /roughly 500 characters/);
  assert.doesNotMatch(system, /## Memory Signals/);
  assert.doesNotMatch(system, /Memory Signals/);
});

test('session memory prompt preserves the current extraction schema', () => {
  const template = loadPromptTemplate('thread_extracting');
  const system = template.system;

  assert.match(system, /Extraction block shape: metadata comment, `### Title`, `### Summary`, optional `### Content`; separate blocks with `----`/);
  assert.match(system, /### Instruction Signals/);
  assert.match(system, /`## Instruction Signals`: complete replacement list of future-agent instructions; empty section clears it/);
  assert.match(system, /`## Skill Signals`: complete replacement list of reusable workflow candidates; empty section clears it/);
  assert.match(system, /Bullet formats: Instruction/);
  assert.match(system, /Skill `- \[turn:256 \+1\] Skill name: \.\.\.`/);
  assert.match(system, /Use user prompts as signal evidence/);
  assert.match(system, /non-prompt material is reference-only/i);
  assert.match(system, /Approval-only prompts such as/);
  assert.match(system, /Write signals as direct future-agent instructions/);
  assert.match(system, /Cover standing preferences, behavior corrections, edit\/review style, recurring environment quirks, explicit remember\/reuse requests, simple reusable workflows, and narrow repo\/module boundaries/);
  assert.match(system, /Exclude task-bound facts about the current artifact/);
  assert.match(system, /Keep reusable guidance as an Instruction Signal when it fits in 1-3 concise sentences/);
  assert.match(system, /avoid PR numbers, error strings, feature codenames, today's fix\/debug task, task execution artifacts, assistant-devised plans, command history, and one-off task steps/);
  assert.match(system, /Store details under .*## Skill Details.* only for accepted Skill Signals/);
  assert.match(system, /Each signal section: max 10 top-level bullets/);
  assert.match(system, /Sort by explicit .*10.* evidence, retained contribution sum, current-batch supporting prompt count, then prior order; over budget, drop from the bottom/);
  assert.doesNotMatch(system, /## Memory Signals/);
  assert.doesNotMatch(system, /Memory Signals/);
  assert.doesNotMatch(system, /Open Questions/);
});

test('chat domain prompt defines subject routing boundaries', () => {
  const template = loadPromptTemplate('chat');
  const system = template.system;

  assert.match(system, /Same vs separate routing/);
  assert.match(system, /Keep spans with a subject thread when they complete or refine that subject/);
  assert.match(system, /Route spans to the session thread when they introduce a different subject/);
  assert.match(system, /do not clearly fit an existing subject thread/);
  assert.match(system, /need later derivation/);
  assert.match(system, /Do not route to a subject thread only because spans are adjacent, in the same batch, or mention the same people/);
  assert.doesNotMatch(system, /separate work item/);
  assert.doesNotMatch(system, /Split spans/);
});

test('session memory prompt uses raw turns and returns snapshot content document', () => {
  const template = loadPromptTemplate('thread_extracting');
  const system = template.system;

  assert.match(system, /Tool use/);
  assert.match(system, /get_extraction/);
  assert.match(system, /get_turn/);
  assert.match(system, /get_skill/);
  assert.match(system, /Syntax: `@\[turn:<turnId>\]`/);
  assert.match(system, /Return only a Markdown snapshot patch, not a full snapshot/);
  assert.match(system, /Return only a Markdown snapshot patch/);
  assert.match(system, /`## Instruction Signals`: complete replacement list of future-agent instructions/);
  assert.match(system, /`## Skill Signals`: complete replacement list of reusable workflow candidates/);
  assert.match(system, /Include .*## Extractions/);
  assert.match(system, /`## Skill Details`: optional changed\/removed details for accepted Skill Signals/);
  assert.match(system, /get_extraction.*<= 5 calls/);
  assert.match(system, /get_skill.*<= 1 per skill name/);
  assert.match(system, /get_turn.*<= 3 calls/);
  assert.doesNotMatch(system, /Example input/);
  assert.doesNotMatch(system, /Example output/);
  assert.doesNotMatch(system, /## Memory Signals/);
  assert.doesNotMatch(system, /sourceRefs/);
});

test('project dreamer prompt merges incremental project signals without session refs', () => {
  const template = loadPromptTemplate('project_dreaming');
  const system = template.system;
  assert.match(system, /project signal merge agent/i);
  assert.match(system, /Maintain the current project signal set/);
  assert.match(system, /Merge existing project signals with incremental session signal evidence/);
  assert.match(system, /Return a complete Markdown project signal set, not a patch/);
  assert.match(system, /Existing project signal rows, each labeled with `\[signal:<stable_row_id>\]`/);
  assert.match(system, /Incremental session Instruction Signals and Skill Signals, each labeled with one or more `\[<turn_id> \+<contribution>\]` evidence labels/);
  assert.match(system, /Existing project signal labels identify stored rows; incremental turn labels identify user-prompt evidence/);
  assert.match(system, /Existing `\[signal:\*\]` labels are row identities, not evidence/);
  assert.match(system, /Incremental full-turn-id labels are new evidence/);
  assert.doesNotMatch(system, /lightweight signal/i);
  assert.doesNotMatch(system, /Tool use/);
  assert.doesNotMatch(system, /get_skill/);
  assert.match(system, /Preserve source-supported meaning, scope, constraints, and signal type/);
  assert.match(system, /Merge or update semantically related signals using incremental wording as the latest state/);
  assert.match(system, /include incremental turn labels only when they support the final wording and scope/);
  assert.match(system, /Do not broaden, invent, or reclassify signals/);
  assert.match(system, /Avoid duplicating the same reusable guidance as both an Instruction Signal and a Skill Signal/);
  assert.match(system, /For Skill Signals, merge details when source Skill Signal content supports the same reusable workflow/);
  assert.match(system, /Sources are ordered older to newer; later evidence can replace earlier overlapping content/);
  assert.match(system, /Write direct future-agent instructions in the dominant language of retained source signals/);
  assert.match(system, /preserve identifiers exactly/);
  assert.match(system, /Instruction Signals are concise future-agent operating instructions/);
  assert.match(system, /Skill Signals are reusable workflow entries with a skill name, short summary, and optional reusable details/);
  assert.doesNotMatch(system, /Open Questions:/);
  assert.doesNotMatch(system, /Signal weights/);
  assert.doesNotMatch(system, /Do not cap weights at a fixed maximum/);
  assert.doesNotMatch(system, /Budget/);
  assert.match(system, /Output labels drive deterministic storage upserts/);
  assert.match(system, /Every output signal block must start with exactly one label list/);
  assert.match(system, /Use only labels that appeared in the input/);
  assert.match(system, /\[signal:<stable_row_id>\]` labels identify existing project rows/);
  assert.match(system, /\[<turn_id> \+<contribution>\]` labels identify incremental evidence/);
  assert.match(system, /the first `\[signal:\*\]` is the survivor row/);
  assert.match(system, /Additional `\[signal:\*\]` labels in the same output block are merged into the survivor row and removed from current state/);
  assert.match(system, /If an output block has only turn evidence labels, it creates a new project signal row/);
  assert.match(system, /If an input `\[signal:\*\]` label is omitted from the output, that existing project signal is removed from current state/);
  assert.doesNotMatch(system, /session:<rowid>/);
  assert.doesNotMatch(system, /\(refs:/);
  assert.match(system, /Start with `# Project Signals`/);
  assert.match(system, /Every saved signal content block starts with either `## Instruction Signal` or `## Skill Signal`/);
  assert.match(system, /Skill Signal content starts with `## Skill Signal`, then `### <skill name>`/);
  assert.doesNotMatch(system, /# Project Dream: \{\{project\}\}/);
  assert.doesNotMatch(system, /\[N\]/);
  assert.doesNotMatch(system, /Include `## Signals`/);
  assert.doesNotMatch(system, /Include `### Guidance`, `### Skills`, and `### Open Questions`/);
  assert.match(template.userTemplate, /## Existing Project Signals/);
  assert.match(template.userTemplate, /## Incremental Session Signals/);
  assert.doesNotMatch(template.userTemplate, /## Parent Dream/);
  assert.doesNotMatch(template.userTemplate, /## Incremental Signals/);
  assert.doesNotMatch(template.userTemplate, /## Incremental Lightweight Signals/);
  assert.doesNotMatch(template.userTemplate, /### session:/);
});
